### ISSUE TITLE
Plugin wont update to 3.3.1

### ISSUE THREAD

**Issue by elaltito** [smallmultiples/sketch-chippencharts#1]
Plugin always prompts to be updated from 3.3 to 3.3.1 within Sketch, but clicking on update does not work.
<img width="476" alt="screenshot 2018-11-23 at 02 45 12" src="https://user-images.githubusercontent.com/44484271/48925983-fa4d3080-eec9-11e8-8ac3-90eb9c9e257a.png">

**Comment by Christian-Baptiste** [comment]
Same issue. I constantly get the plugin update message. Clicking on the update button does nothing.

**Comment by monkian** [comment]
Thanks for posting this issue. The manifest contained a version number that was causing trouble. Clicking "Update" in the Sketch plugin preferences should fix the issue now.
